os: linux
dist: bionic
language: cpp
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.14.1-bionic -y
  - sudo apt update
  - sudo apt install libglu1-mesa-dev libgl1-mesa-dev qt514base cppcheck -y

install:
  - wget https://raw.githubusercontent.com/DeuxVis/cpplint/master/cpplint.py
  - chmod +x cpplint.py && mv cpplint.py cpplint
  - source /opt/qt5*/bin/qt5*-env.sh

before_script:
  - echo '<RCC></RCC>' > res/res.qrc # ignore resources inconsistency
  - /opt/qt5*/bin/qmake PREFIX=/usr || cmake CMakeLists.txt

script:
  - make -j
  - rm ./qrc_* || true
  - rm ./moc* || true
  - rm ./ui* || true
  - rm -rf ./box2d || true
  - files=$(find -name '*.h' -o -name '*.cpp')
  - cppcheck --enable=unusedFunction --language=c++ $files
  - cppcheck --enable=warning,performance --language=c++ --error-exitcode=1 $files
  - ./cpplint --filter=-legal/copyright,-build/include_subdir,-build/c++11,-build/header_guard,-build/include_order --root=src $files
